title: "Generalization over Enumeration: Mathematical Ideas for Python Testing"
author: Roberto Abdelkader Martínez Pérez
copyright: "2025"

latex:
  latex_documents:
    targetname: generalization-over-enumeration.tex

execute:
  execute_notebooks: force

html:
  use_issues_button: true
  use_repository_button: true

repository:
  url: https://github.com/nilp0inter/generalization-over-enumeration-book
  path_to_book: ""

sphinx:
  config:
    project: generalization-over-enumeration
    today: "2025"
    today_fmt: "%Y"
    html_theme_options:
      repository_url: https://github.com/nilp0inter/generalization-over-enumeration-book
      use_repository_button: true
      use_issues_button: true